### ISSUE TITLE
Search results for all search keywords are not used in semantic scholar retriever

### ISSUE THREAD

**Issue by ryamauchi** [auto-res/researchgraph#52]
The search results for each keyword are stored in `all_search_results`. 
However, only the last `results` of `all_search_results` is used to actually download articles from arXiv.
See below:
https://github.com/auto-res/researchgraph/blob/develop/researchgraph/retrievenode/semantic_scholar.py#L111

**Comment by NamelessOgya** [comment]
I am facing a similar issue in the implementation of the arXiv node.
I believe I have identified the cause.

The list of keywords input by the user is initially stored in keywords_list:
  
```
for search_term in keywords_list:
    results = sch.search_paper(search_term, limit=self.num_retrieve_paper)
    all_search_results.append(results)

```  
At this point, the number of papers stored in all_search_results is equal to the number of keywords multiplied by `self.num_retrieve_paper`.

However, when actually downloading the papers, only the first self.num_retrieve_paper results from the list are being downloaded, as shown in the code below:


`self.download_from_arxiv_ids(arxiv_ids[:self.num_retrieve_paper])`

I believe there are two possible solutions to this issue:

### 1. Adjust the number of papers to be retrieved for each keyword.
For example, if there are n keywords, retrieve approximately self.num_retrieve_paper / n papers for each keyword so that the total number of papers equals self.num_retrieve_paper.

This approach maintains the total number of papers at self.num_retrieve_paper, but there are potential issues, such as how to handle cases where self.num_retrieve_paper is not divisible by n.

### 2. Change the specification to retrieve self.num_retrieve_paper papers for each keyword.
Retrieve `self.num_retrieve_paper` papers for each keyword. By simply modifying the download line to:

`self.download_from_arxiv_ids(arxiv_ids)`
You can retrieve self.num_retrieve_paper papers per keyword, resulting in a total of `number_of_keywords` × `self.num_retrieve_paper papers`.
